package io.github.bayonle010.escrow.escrow.shared.api;

public enum ErrorCode {
    REQUEST_VALIDATION_FAILED,
    REQUEST_BODY_INVALID,
    ESCROW_AMOUNT_INVALID,
    ESCROW_PARTICIPANTS_MUST_DIFFER,
    ESCROW_CREATOR_NOT_PARTICIPANT,
    ESCROW_UNSUPPORTED_CURRENCY,
    ESCROW_DELIVERY_DEADLINE_INVALID,
    INTERNAL_SERVER_ERROR
}
