package io.github.bayonle010.escrow.ledger.shared.api;

public enum ErrorCode {
    REQUEST_VALIDATION_FAILED,
    REQUEST_BODY_INVALID,
    INTERNAL_EVENT_UNAUTHORIZED,
    EVENT_VERSION_UNSUPPORTED,
    EVENT_ID_CONFLICT,
    FUNDING_EVENT_CONFLICT,
    LEDGER_ACCOUNT_NOT_FOUND,
    LEDGER_POSTING_FAILED,
    INTERNAL_SERVER_ERROR
}
