package io.github.bayonle010.escrow.payment.shared.api;

public enum ErrorCode {
    REQUEST_VALIDATION_FAILED,
    REQUEST_BODY_INVALID,
    IDEMPOTENCY_KEY_REQUIRED,
    IDEMPOTENCY_KEY_INVALID,
    IDEMPOTENCY_KEY_REUSED,
    ESCROW_NOT_FOUND,
    ESCROW_SERVICE_UNAVAILABLE,
    ESCROW_STATE_INVALID,
    ESCROW_TERMS_EXPIRED,
    PAYER_NOT_BUYER,
    PAYMENT_ALREADY_EXISTS,
    PAYMENT_NOT_FOUND,
    PAYMENT_OUTCOME_CONFLICT,
    PROVIDER_CALLBACK_UNAUTHORIZED,
    PROVIDER_REFERENCE_REUSED,
    INTERNAL_SERVER_ERROR
}
